postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: yelp_clone_<%= ENV['RAILS_ENV'] %>
  min_messages: ERROR

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: yelp_clone_development

test:
  <<: *default
  database: yelp_clone_test

production:
  <<: *default
  database: yelp_clone_production
  username: yelp_clone
  password: <%= ENV['YELP_CLONE_DATABASE_PASSWORD'] %>
